Updated personal social media Links
Albert221/gci-winners pull request #20
Opened 2019-10-14 19:56 UTC by sidhyatikku

I added some more social media links

2019-10-15 16:31 UTC, Albert221 requested changes

2019-10-15 16:31 UTC, Albert221 commented on _winners/sidhya-tikku.md
> +        icon: dribbble
You have Dribbble twice here

2019-10-18 15:02 UTC, sidhyatikku commented on _winners/sidhya-tikku.md
> +        icon: dribbble
ahhh snap

2019-10-18 15:03 UTC, sidhyatikku commented on _winners/sidhya-tikku.md
> +        icon: dribbble
@Albert221 done

2019-10-29 13:20 UTC, Albert221 approved these changes

2019-10-29 13:21 UTC, merged