Added myself to the list
Albert221/gci-winners pull request #5
Opened 2019-10-01 15:46 UTC by Adrijaned

2019-10-01 15:48 UTC, Albert221 requested changes

2019-10-01 15:48 UTC, Albert221 commented on _winners/jindrich_dite.md
> +org: MovingBlcoks
You have a typo here

2019-10-02 14:29 UTC, Adrijaned commented on _winners/jindrich_dite.md
> +org: MovingBlcoks
Whoops! Fixed

2019-10-02 14:37 UTC, Albert221 approved these changes

2019-10-02 14:37 UTC, merged